name: CI
on: [pull_request]
jobs:
  test_and_lint:
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_GRAPH_CMS_ENDPOINT: '${{ secrets.NEXT_PUBLIC_GRAPH_CMS_ENDPOINT}}'
      NEXT_PUBLIC_GRAPH_CMS_TOKEN: ${{ secrets.NEXT_PUBLIC_GRAPH_CMS_TOKEN}}
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn
      - name: Run all linting tests
        run: yarn lint
      - name: Run unit tests
        run: yarn test
