name: Test_Coverage
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  run-test-coverage-workflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn
      - name: Run tests with coverage
        run: |
          SUMMARY="$(yarn test --coverage --coverageReporters=text-summary | tail -3 | head -1)"
          TOKENS=($SUMMARY)
          echo "COVERAGE=$(echo ${TOKENS[2]})" >> $GITHUB_ENV
      - name: Create the Coverage Badge
        uses: schneegans/dynamic-badges-action@v1.1.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: 5734448c5f2e10915c1d4e45ad04dd25
          filename: next-ts-graphql-blog_test_coverage.json
          label: Test Coverage
          message: ${{ env.COVERAGE }}
          namedLogo: jest
          color: blue
          logoColor: lightblue
      - name: Update the Badge URL in the pull request body
        run: |
          BODY=$(curl -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/teofanis/next-ts-graphql-blog/pulls/${{ github.event.pull_request.number }} | jq .body | sed -En "s/protocol__pull_##.json/protocol__pull_${{ github.event.pull_request.number }}.json/p")
          JSON="{\"body\":$(echo $BODY | jq -sR .)}"
          curl \
            -X POST \
            -H "Authorization: token ${{ secrets.GIST_SECRET }}" \
            -H "Content-Type: application/json" \
            -d $JSON \
            https://api.github.com/repos/teofanis/next-ts-graphql-blog/pulls/${{ github.event.pull_request.number }}
